//BrandCatReducer
export const BRANDCAT_LOADING = 'BRANDCAT_LOADING'
export const BRANDCAT_ERROR = 'BRANDCAT_ERROR'
export const BRANDCAT_FETCH_SUCCESS = 'BRANDCAT_FETCH_SUCCESS'

//BrandReducer
export const BRAND_LOADING = 'BRAND_LOADING'
export const BRAND_ERROR = 'BRAND_ERROR'
export const BRANDLIST_FETCH_SUCCESS = 'BRANDLIST_FETCH_SUCCESS'
export const BRANDBYCATEGORY_FETCH_SUCCESS = 'BRANDBYCATEGORY_FETCH_SUCCESS'

//CarouselReducer
export const CAROUSEL_CONTENT_FETCHED = 'CAROUSEL_CONTENT_FETCHED'

//CategoryReducer
export const CATEGORY_LOADING = 'CATEGORY_LOADING'
export const CATEGORY_ERROR = 'CATEGORY_ERROR'
export const CATEGORY_FETCH_SUCCESS = 'CATEGORY_FETCH_SUCCESS'
export const MOSTPARENT_FETCH_SUCCESS = 'MOSTPARENT_FETCH_SUCCESS'
export const MOSTCHILD_FETCH_SUCCESS = 'MOSTCHILD_FETCH_SUCCESS'
export const CHILD_FETCH_SUCCESS = 'CHILD_FETCH_SUCCESS'
export const CHILDOFMAINPARENT_FETCH_SUCCESS = 'CHILDOFMAINPARENT_FETCH_SUCCESS'
export const SELECT_CAT = 'SELECT_CAT'
export const SELECT_CHILD_CAT = 'SELECT_CHILD_CAT'
export const SELECT_FILTER_CAT = 'SELECT_FILTER_CAT'
export const CATEGORIES_SEARCH_FILTER = 'CATEGORIES_SEARCH_FILTER'

//ChangeStyleReducer
export const CHANGE_STYLE = 'CHANGE_STYLE'

//CourierReducer
export const COURIER_FETCHED = 'COURIER_FETCHED'
export const SELECT_COURIER = 'SELECT_COURIER'
export const COURIER_EMPTY = 'COURIER_EMPTY'

//FormProductReducer
export const CATLIST_CHANGE = 'CATLIST_CHANGE'
export const NEWCATEGORIES_CHANGE = 'NEWCATEGORIES_CHANGE'
export const NEWPRODUCT_CHANGE = 'NEWPRODUCT_CHANGE'
export const IMAGE_CHANGE = 'IMAGE_CHANGE'
export const INITIALFORMPRODUCT = 'INITIALFORMPRODUCT'
export const FORMDETAILPRODUCT = 'FORMDETAILPRODUCT'
export const IMAGEWILLDELETE = 'IMAGEWILLDELETE'

//FormRegisterReducer
export const REGISTER_INPUT_ALLCHANGE = 'REGISTER_INPUT_ALLCHANGE'
export const REGISTER_INPUT_CHANGE = 'REGISTER_INPUT_CHANGE'
export const CITY_LIST_FETCH_SUCCESS = 'CITY_LIST_FETCH_SUCCESS'
export const REGISTER_INPUT_INITIAL = 'REGISTER_INPUT_INITIAL'
export const REGISTER_USER_INPUT_INITIAL = 'REGISTER_USER_INPUT_INITIAL'

//ManageUserReducer
export const USERLIST_LOADING = 'USERLIST_LOADING'
export const USERLIST_ERROR = 'USERLIST_ERROR'
export const USERLIST_FETCHED = 'USERLIST_FETCHED'
export const USERCOUNT_FETCHED = 'USERCOUNT_FETCHED'

//ProductCatReducer
export const PRODUCTCAT_LOADING = 'PRODUCTCAT_LOADING'
export const PRODUCTCAT_ERROR = 'PRODUCTCAT_ERROR'
export const PRODUCTCAT_FETCH_SUCCESS = 'PRODUCTCAT_FETCH_SUCCESS'

//ProductDetailReducer
export const PRODUCTDETAIL_FETCH_SUCCESS = 'PRODUCTDETAIL_FETCH_SUCCESS'
export const INITIALPRODUCTDETAIL = 'INITIALPRODUCTDETAIL'

//ProductReducer
export const PRODUCT_LOADING = 'PRODUCT_LOADING'
export const PRODUCT_ERROR = 'PRODUCT_ERROR'
export const PRODUCTLIST_FETCH_SUCCESS = 'PRODUCTLIST_FETCH_SUCCESS'
export const PRODUCTLISTCOUNT_FETCH_SUCCESS = 'PRODUCTLISTCOUNT_FETCH_SUCCESS'
export const UNCATEGORIZEDPRODUCTLIST_FETCH_SUCCESS = 'UNCATEGORIZEDPRODUCTLIST_FETCH_SUCCESS'
export const PRODUCTLISTBYCATEGORY_FETCH_SUCCESS = 'PRODUCTLISTBYCATEGORY_FETCH_SUCCESS'
export const PRODUCTLISTBYCATEGORYCOUNT_FETCH_SUCCESS = 'PRODUCTLISTBYCATEGORYCOUNT_FETCH_SUCCESS'

//UserCartReducer
export const USER_CART_LOADING = 'USER_CART_LOADING'
export const USER_CART_FETCHED = 'USER_CART_FETCHED'
export const USER_CART_ERROR = 'USER_CART_ERROR'

//UserBuildReducer
export const USER_BUILD_LOADING = 'USER_BUILD_LOADING'
export const USER_BUILD_FETCHED = 'USER_BUILD_FETCHED'
export const USER_BUILD_ERROR = 'USER_BUILD_ERROR'

//UserReducer
export const USER_LOADING = 'USER_LOADING'
export const USER_ERROR = 'USER_ERROR'
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
export const RESEND_VERIFICATION_SUCCESS = 'RESEND_VERIFICATION_SUCCESS'
export const SEND_EMAIL_RESETPASS_SUCCESS = 'SEND_EMAIL_RESETPASS_SUCCESS'
export const RESETPASS_SUCCESS = 'RESETPASS_SUCCESS'

//UserTransactionReducer
export const USER_TRANSACTION_LIST = 'USER_TRANSACTION_LIST'
export const USER_TRANSACTION_LISTALLCOUNT = 'USER_TRANSACTION_LISTALLCOUNT'
export const USER_TRANSACTION_DETAIL = 'USER_TRANSACTION_DETAIL'
export const USER_TRANSACTION_HISTORY = 'USER_TRANSACTION_HISTORY'
export const USER_TRANSACTION_ERROR = 'USER_TRANSACTION_ERROR'
export const USER_TRANSACTION_LOADING = 'USER_TRANSACTION_LOADING'
export const USER_TRANSACTION_SELECTED = 'USER_TRANSACTION_SELECTED'
export const USER_TRANSACTION_RECEIPT = 'USER_TRANSACTION_RECEIPT'
export const USER_TRANSACTION_RECEIPT_ERROR = 'USER_TRANSACTION_RECEIPT_ERROR'
export const USER_TRANSACTION_EDIT_SUCCESS = 'USER_TRANSACTION_EDIT_SUCCESS'

//UserWishlistReducer
export const USER_WISHLIST_LOADING = 'USER_WISHLIST_LOADING'
export const USER_WISHLIST_FETCHED = 'USER_WISHLIST_FETCHED'
export const USER_WISHLIST_ERROR = 'USER_WISHLIST_ERROR'
export const USER_WISHLIST_EMPTY = 'USER_WISHLIST_EMPTY'
